image: python:latest

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - pip install -r requirements.txt
  - pip install -r ci/pylint_requirements.txt

test:
  script:
    - python meta_social/manage.py test $(ls meta_social/apps)
    - pip cache dir
  only:
    - devel

pylint:
  script:
    - ci/pylint_runner.sh
  only:
    - devel
