image: docker:latest

variables:
  DOCKER_DRIVER: overlay

services:
- docker:dind

before_script:
- docker info

build:
  stage: build
  script:
    - sudo apt install -y python-pip
    - pip install docker-compose
    - docker-compose up --build
