image: python:latest

cache:
  paths:
  - /root/.cache/pip/

before_script:
  - pip install -r requirements.txt
  - pip install -r ci/pylint_requirements.txt

test:
  script:
    - ci/tests_runner.sh
  only:
    - devel

pylint:
  script:
    - ci/pylint_runner.sh
  only:
    - devel
  artifacts:
    paths:
      - public/pylint.svg
      - public/pylint.html

test_coverage:
  script:
    - cd meta_social
    - coverage run manage.py test
    - coverage report -m apps/*/*.py
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'