version: '3'

services:
  social:
    build:
      context: .
    ports:
      - 80:80
    command: ./docker-entrypoint.sh
    depends_on:
      - db
      - redis
    container_name: social
    volumes:
      - ./:/code

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DB
    container_name: db

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always