version: '3'

services:
  social:
    build:
      context: .
    ports:
      - 80:80
      - 443:443
    command: ./docker-entrypoint.sh
    depends_on:
      - db
      - redis
    container_name: social
    volumes:
      - ./:/code

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DB
    container_name: db

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    restart: always
  
  smtp:
    image: namshi/smtp
    restart: always
    ports:
      - '25:25'
    volumes:
      - ./:/code
    environment: 
      - KEY_PATH=/code/config/privkey.pem
      - CERTIFICATE_PATH=/code/config/certkey.pem
