version: '3'

services:
  social:
    build:
      context: .
    ports:
      - 80:80
    command: ./docker-entrypoint.sh
    depends_on:
      - db
    container_name: social

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: DB
    container_name: db